sudo: required

language: node_js

node_js:
- v6

services:
  - docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

script:
  - npm test -- -i --coverage

env:
  global:
  - CXX=g++-4.8
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t north2south/web .;
    docker login --username=_ --password="$HEROKU_TOKEN" registry.heroku.com;
    docker push north2south/web;
    fi
