version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"