version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    links:
      - mongo
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/aurelia-app/node_modules
  mongo:
    image: mongo
    ports:
      - "27017:27017"