version: "3"
services:
  web:
    build: .
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "80:8080"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"